
KBUILD_CFLAGS	+= -Idrivers/nand/inc/ \
		-Idrivers/nand/manager_v1.6.2/inc/ \
		-Idrivers/nand/manager_v1.6.2/inc/os/

obj-y		+= os/NandAlloc.o os/NandSemaphore.o \
		os/NandThread.o os/clib.o os/nanddebug.o

obj-y		+= nm_interface.o
